### ISSUE TITLE
Captcha

### ISSUE THREAD

**Issue by kdog2018** [openbullet/openbullet#10]
Can't get any config with captcha to work with this new open bullet. What settings to look for to make it work like black bullet ?

**Comment by Choempie** [comment]
Should be all the same, Did you enter your key?

**Comment by kdog2018** [comment]
yep ... so working for you ??

**Comment by openbullet** [comment]
Please provide more information such as the specific service you are using and a test URL to try on. I have credit on every service so I can test.

**Comment by kdog2018** [comment]
using dbc my login is correct as works with black bullet. Also when I add proxies even though change to socks4 still adds as http if that matters.

**Comment by Choempie** [comment]
> yep ... so working for you ??

I just made one with captcha

**Comment by kdog2018** [comment]
you mean made a config and working with open bullet ? what captcha service ? also any problems with proxies and adding socks4 ones always puts them in http section

**Comment by Choempie** [comment]
> you mean made a config and working with open bullet ? what captcha service ? also any problems with proxies and adding socks4 ones always puts them in http section

ye made a config with captcha with open bullet, Using AntiCaptcha, Works fine idk about the proxies

**Comment by kdog2018** [comment]
hmm wonder what's wrong with mine

**Comment by GHETTODUB** [comment]
> Please provide more information such as the specific service you are using and a test URL to try on. I have credit on every service so I can test.

{"$type":"System.Collections.Generic.List`1[[RuriLib.BlockBase, RuriLib]], mscorlib","$values":[{"$type":"RuriLib.BlockRecaptcha, RuriLib","VariableName":"RECAP","Url":"https://www.*********.com/custom/************/landing.aspx","SiteKey":"6****U8UAAAAAGJ-xDkiKvXShnrAcxPBL3******","Label":"RECAPTCHA","Disabled":false

[TWOCAPTCHA]
SOLVING REcAPTCHA....
ERROR: CAPCHA_NOT_READY

**Comment by GHETTODUB** [comment]
test URL https://patrickhlauke.github.io/recaptcha/
SITE KEY 6Ld2sf4SAAAAAKSgzs0Q13IZhY02Pyo31S2jgOB5

**Comment by winuser** [comment]
TWOCAPTCHA]
SOLVING REcAPTCHA....
ERROR: CAPCHA_NOT_READY

Same issue

**Comment by kdog2018** [comment]
where u see that in the log ?

**Comment by vurezo** [comment]
Replace in source
NOTREADY
with CAPCHA_NOT_READY
both occurrences

**Comment by Crackingforum** [comment]
I can confirm the bug while using Two captcha in Open Bullet.Here is the screenshot which will explain everything.You will see that it is working fine in the BB and not working in OB.
![Cattura](https://user-images.githubusercontent.com/49287002/55577226-60b54b80-5713-11e9-99c5-ec6b94d7db67.PNG)

**Comment by kdog2018** [comment]
open bullet doesn't work with dbc either

**Comment by Cheetah55** [comment]
I have the same problem.(Cptcha and Re-cptcha )  Please let us use BlackBullet until these problems are corrected. And different problem Wordlist Min & Max.  There seems to be a different problem here if you control it would be very sevinirim.

<--- Executing Block CAPTCHA --->
Checking balance...
ERROR: Error converting value 555 to type 'RuriLib.CaptchaServices.TwoCaptcha+GenericResponse'. Path '', line 1, position 8.

ERROR: Error converting value 555 to type 'RuriLib.CaptchaServices.TwoCaptcha+GenericResponse'. Path '', line 1, position 8.

**Comment by Cheetah55** [comment]
Capmonster for problem this :

Checking balance...
ERROR: Error converting value 555 to type 'RuriLib.CaptchaServices.TwoCaptcha+GenericResponse'. Path '', line 1, position 8.
===== DEBUGGER ENDED AFTER 0,67985 SECOND(S) WITH STATUS: ERROR =====

**Comment by openbullet** [comment]
Guys @winuser @GHETTODUB the 2captcha issue was solved on this commit https://github.com/openbullet/openbullet/commit/96fc6ef642c67e8f1462ce7cc1c51bbba89c8092

**Comment by Cheetah55** [comment]
how do I get this into a package ? I don't know how to defragment the program. Please send me a tutorial link for this.

**Comment by Crackingforum** [comment]
Yeah, me too, would like to know how to apply the changes and thanks @openbullet for giving us this tool.

**Comment by Cheetah55** [comment]
# How to compile
1. Clone the [official Extreme.Net repository](https://github.com/nickolasKrayn/Extreme.Net).
2. **Compile** it and obtain the **Extreme.Net.dll** file. You will find it inside the folder Extreme.Net/bin/Debug.
3. **Clone this repository** and open it in Visual Studio.
4. Right click on each of the 3 projects and from the menu select **Add > Reference**.
5. Add the previously compiled **Extreme.Net.dll** file and click OK.
6. Switch to **Release** mode for a much cleaner output.
7. **Compile** the solution (Visual Studio will fetch all the missing nuget packages).
8. You can find the compiled projects under OpenBullet/bin/Release and OpenBulletCLI/bin/Release.

**Comment by Cheetah55** [comment]
i do, replace files but same problem 

<--- Executing Block CAPTCHA --->
Checking balance...
ERROR: Error converting value 555 to type 'RuriLib.CaptchaServices.TwoCaptcha+GenericResponse'. Path '', line 1, position 8.
WARNING: The test input data did not respect the validity regex for the selected wordlist type!

**Comment by Crackingforum** [comment]
After following the steps How to compile, i can confirm, it isn't working and nothing has been changed regarding this issue.

**Comment by Greenbug1** [comment]
> After following the steps How to compile, i can confirm, it isn't working and nothing has been changed regarding this issue.

Same i can confirm this is still not working

**Comment by openbullet** [comment]
Is this bug only happening with CapMonster / XEvil? I think it's because I use the query `json=1` when calling the actual 2captcha site, while CapMonster / XEvil doesn't support it and replies with just the balance number. So I'd need to adjust it the same way I did it for the DeathByCaptcha class. Please tell me if you're using one of those 2 softwares so I can pinpoint the issue and fix it.

**Comment by Cheetah55** [comment]
I'm using 2 captcha system. I not have blance TwoCaptcha sory.

1- imagetyper result (work)

<--- Executing Block CAPTCHA --->
Checking balance...
[ImageTypers] Current Balance: $2,2546
Downloading image...
Succesfully got the response: UXmX75
Response stored in variable: CAP
<--- Executing Block REQUEST --->

2 - Capmonster Result ( Not Work )

<--- Executing Block CAPTCHA --->
Checking balance...
ERROR: Error converting value 555 to type 'RuriLib.CaptchaServices.TwoCaptcha+GenericResponse'. Path '', line 1, position 8.
===== DEBUGGER ENDED AFTER 0,7178837 SECOND(S) WITH STATUS: ERROR =====

**Comment by Crackingforum** [comment]
> 
> 
> Is this bug only happening with CapMonster / XEvil? I think it's because I use the query `json=1` when calling the actual 2captcha site, while CapMonster / XEvil doesn't support it and replies with just the balance number. So I'd need to adjust it the same way I did it for the DeathByCaptcha class. Please tell me if you're using one of those 2 softwares so I can pinpoint the issue and fix it.

Hello BB!

Me and an another user (Cheetah) are using Capmonster pro and we can confirm the issue exists and please checky my screenshot i posted 2 days ago and you will see that it works with the old BB and not with the Open bullet.

Thanks again for your time,dedication and effort, God bless you.

**Comment by Cheetah55** [comment]
> > Is this bug only happening with CapMonster / XEvil? I think it's because I use the query `json=1` when calling the actual 2captcha site, while CapMonster / XEvil doesn't support it and replies with just the balance number. So I'd need to adjust it the same way I did it for the DeathByCaptcha class. Please tell me if you're using one of those 2 softwares so I can pinpoint the issue and fix it.
> 
> Hello OB!
> 
> Me and an another user (Cheetah) are using Capmonster pro and we can confirm the issue exists and please checky my screenshot i posted 2 days ago and you will see that it works with the old BB and not with the Open bullet.
> 
> Thanks again for your time,dedication and effort, God bless you.

Yes right. and I have other friends who are experiencing this issue.

**Comment by sieunhando** [comment]
Me too. Capmonster not work in the last version. It send a request to Capmonster, but not wait it response the result (capmonster still working but the program not wait for it).

This is an error:
`
Solving reCaptcha...
ERROR: Unexpected character encountered while parsing value: C. Path '', line 0, position 0.`

**Comment by openbullet** [comment]
Yeah guys don't worry I am perfectly aware of what's causing this and will work on it after version 1.0.1 so hang in there! This will be most definitely fixed next week!

**Comment by kdog2018** [comment]
waited for 1.0.1 but still having issues with dbc and xevil works great with black bullet but not openbullet

Anyone else still have same issues ?

**Comment by winuser** [comment]
can someone confirm whether 1.0.1 2captcha is working with capmonster?

**Comment by Cheetah55** [comment]
> Yeah guys don't worry I am perfectly aware of what's causing this and will work on it after version 1.0.1 so hang in there! This will be most definitely fixed next week!

you're really doing this for us.Thank you so much openbb.

King Regards.

**Comment by Crackingforum** [comment]
Still seeing for help.

**Comment by kdog2018** [comment]
any fix yet ?

**Comment by Cheetah55** [comment]
Mr. openbb please continue to use version 2.5.1. This version works very stable and there is no problem.

**Comment by openbullet** [comment]
Fixed https://github.com/openbullet/openbullet/commit/476333c1d3a786a8b2e01927333a905e650dd0a4

**Comment by kdog2018** [comment]
still not working for me think my env.ini settings wrong working for others ?

**Comment by Cheetah55** [comment]
stil not workning :( 

now different error have 

<--- Executing Block CHECK_BANN --->
<--- Executing Block PARSE_BOT --->
Parsed variable | Name: BOT | Value: c80d084cc9ed19b8dbd2b6f5f6ee7f11

<--- Executing Block CAPTCHA --->
Checking balance...
[TwoCaptcha] Current Balance: $555
Downloading image...
### ERROR
ERROR: ERROR
<--- Executing Block FUNCTION --->
Executed function ToUppercase on input <CAP> with outcome <CAP>
Parsed variable | Name: UPP | Value: <CAP>

**Comment by openbullet** [comment]
@Cheetah55  I tested with reCaptcha and it was working fine. If you're having issues with normal captchas please open another issue and provide a detailed explanation e.g. with a captcha image link so we can reproduce it easily and find out the issue. Also did you try using a normal 2captcha account without CapMon / XEvil? Do you get the same error?
