### ISSUE TITLE
Errore modulo cloudflare 

### ISSUE THREAD

**Issue by alex94we** [openbullet/openbullet#12]
Noto un problema nel cloudflare bypass praticamente nel config maker la config funziona(config su iptvstreaming.org) rilevo se un account e valido o meno. 
Una volta inserita nel runner il blocco cloudflare bypass va in errore.. allego i log su pastebin:

Debug nel config maker: 

> [03/04/2019 10:50:27] (Info) Stacker - Started the debugger
[03/04/2019 10:50:27] (Info) Stacker - Converting Observables
[03/04/2019 10:50:27] (Info) Stacker - Initializing the request data
[03/04/2019 10:50:27] (Info) Stacker - Setting the first block as the current block
[03/04/2019 10:50:33] (Info) Stacker - Processed BYPASSCF "https://ip [...]
[03/04/2019 10:50:33] (Info) Stacker - Processed REQUEST GET "https:/ [...]
[03/04/2019 10:50:33] (Info) Stacker - Processed PARSE "<SOURCE>" LR  [...]
[03/04/2019 10:50:34] (Info) Stacker - Processed #Login REQUEST POST  [...]
[03/04/2019 10:50:34] (Info) Stacker - Processed KEYCHECK BanOnToChec [...]
[03/04/2019 10:50:34] (Info) Stacker - Processed KEYCHECK BanOnToChec [...]
[03/04/2019 10:50:34] (Info) Stacker - Debugger completed

Debug nel runner: 

> [03/04/2019 10:55:14] (Info) Runner - Set up sound players
[03/04/2019 10:55:14] (Info) Runner - Setting up the background worker
[03/04/2019 10:55:14] (Info) Runner - Started the Master Worker
[03/04/2019 10:55:14] (Info) Runner - Loaded 44343 lines
[03/04/2019 10:55:14] (Info) Runner - Using Proxies: False
[03/04/2019 10:55:14] (Info) Runner - Creating bot 1
[03/04/2019 10:55:14] (Info) Runner - Trying to assign data a.burgio@hotmail.it:artjob
[03/04/2019 10:55:14] (Info) Runner - Assigned data a.burgio@hotmail.it:artjob to bot 1
[03/04/2019 10:55:14] (Info) Runner - [1] started with data a.burgio@hotmail.it:artjob
[03/04/2019 10:55:14] (Info) Runner - Trying to assign data a.buttignon@hotmail.it:ndb060674
[03/04/2019 10:55:24] (Error) Runner - [1] ERROR in block BYPASS CF | Exception: Riferimento a un oggetto non impostato su un'istanza di oggetto.
[03/04/2019 10:55:25] (Info) Runner - [1] Ended with result ERROR
[03/04/2019 10:55:27] (Info) Runner - Sent cancellation request to Master Worker

alche ho provato anche a creare una config solo con il blocco cloudflare e fornisce sempre lo stesso errore ...

spero di essere stato abbastanza chiaro

**Comment by openbullet** [comment]
I will look into it for sure

**Comment by openbullet** [comment]
By the way please write in English nex time thanks.

**Comment by mastercho** [comment]
i tried the lib weeks ago and was getting same error on my projects

**Comment by openbullet** [comment]
Leaf.xNet has this problem currently, until they fix I cannot do much, unless I decide to switch to the other CF bypass library available for C#

**Comment by ruz0ne** [comment]
hey is there any update ? i have the same problem its working only fine in the debugger... do you think leaf.xnet will fix the problem soon ?

thank you

**Comment by openbullet** [comment]
I switched to another library, this is now fixed.

**Comment by mastercho** [comment]
whats point when on new library still persists the same issue. The same error pops up in different random places, proxy manager, runner etc... So the issue was not the lib at all

**Comment by openbullet** [comment]
@mastercho Those errors are due to the proxy not working, it's not a CF error. Also mind that SOCKS proxies don't work with this library, so use HTTP ones.

**Comment by mastercho** [comment]
I give just example, used HTTP and proxies work same as before, just CF block in 1.1.1 acts same as before so lib does the same thing throws the same exception, just need to find the issue where is and fix and revert to an old lib as does support SOCKS

**Comment by openbullet** [comment]
@mastercho Can you give me a website to test this on? Because it's working fine for me.

**Comment by mastercho** [comment]
nevermind seems fails only on 99rdp.com when CF detects and blocks cookies and need to renew cookies but "Don't use same cookies" is not ticked
